apiVersion: v1
kind: Service
metadata:
  name: jetty-2-service
  labels:
    app: jetty-2
spec:
  ports:
    - port: 8080
      name: jetty-2-http
  selector:
    app: jetty-2
    tier: frontend
  type: ClusterIP
