apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
spec:
  ports:
    - port: 8080
      name: tomcat-http
  selector:
    app: tomcat
    tier: frontend
  type: ClusterIP