apiVersion: v1
kind: Service
metadata:
  name: jetty-service
  labels:
    app: jetty
spec:
  ports:
    - port: 8080
      name: jetty-http
  selector:
    app: jetty
    tier: frontend
  type: LoadBalancer
