apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv-volume
  labels:
    type: local
spec:
  storageClassName: tomcat
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pv-claim
spec:
  storageClassName: tomcat
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi