apiVersion: v1
kind: Service
metadata:
  name: teralco-frontend-service
  namespace: teralco-web-namespace
  labels:
    app: teralco-frontend
spec:
  type: NodePort
  ports:  
  - name: http
    # port tiene que existir, pero lo que vale de verdad es el valor en nodePort
    port: 80
    targetPort: 80
    nodePort: 30004
    protocol: TCP
  selector:
    app: teralco-frontend
    tier: frontend